{"data":[{"id":"menu_khgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"bj_fs_decoration","text":"会员管理","url":"","seq":2,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{"id":"menu_yzgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_khgl","text":"业主管理","url":"/center/decoration/owner/owner_list/init.htm","seq":21,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_fwry","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_khgl","text":"服务人员","url":"","seq":22,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_hysh","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_khgl","text":"会员审核","url":"","seq":23,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},

{"id":"menu_hysh1","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_hysh1","text":"会员审核11","url":"","seq":23,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]}

]},{"id":"menu_zxgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"bj_fs_decoration","text":"装修管理","url":"","seq":3,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{"id":"menu_zxgl_zxgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxgl","text":"装修管理(子)","url":"","seq":31,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_zxpz","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxgl","text":"装修配置","url":"","seq":32,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{"id":"menu_gxpz","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxpz","text":"工序配置","url":"/center/decoration/process/process_list/init.htm","seq":321,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_gzfy","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxpz","text":"工种费用","url":"","seq":322,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]}]},{"id":"menu_spk","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxgl","text":"商品库","url":"","seq":33,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{
                            "id":"menu_gxpz",
                            "role_id":"8bbd36b65cd34adcb098229eb92ba1b2",
                            "is_delete":1,
                            "pid":"menu_zxpz",
                            "text":"工序配置",
                            "url":"/center/decoration/process/process_list/init.htm",
                            "seq":321,
                            "menu_icon":"menu-icon fa fa-desktop",
                            "is_backend":-1,
                            "hasChildren":false,
                            "children":[

                            ]
                        }]},{"id":"menu_kfjl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxgl","text":"客服记录","url":"","seq":34,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_tjfx","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_zxgl","text":"统计分析","url":"","seq":35,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]}]},{"id":"menu_gysgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"bj_fs_decoration","text":"供应商管理","url":"","seq":4,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{"id":"menu_gysgl_gysgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_gysgl","text":"供应商管理(子)","url":"/center/vendor/vendor/vendor_list/init.htm","seq":41,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]},{"id":"menu_cgddgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_gysgl","text":"采购订单管理","url":"","seq":42,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]}]},{"id":"menu_cwgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"bj_fs_decoration","text":"财务管理","url":"","seq":5,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":true,"children":[{"id":"menu_cwgl_cwgl","role_id":"8bbd36b65cd34adcb098229eb92ba1b2","is_delete":1,"pid":"menu_cwgl","text":"财务管理(子)","url":"","seq":51,"menu_icon":"menu-icon fa fa-desktop","is_backend":-1,"hasChildren":false,"children":[]}]}]}
